# Generated by Django 4.2 on 2023-12-16 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0003_resume_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="skills",
        ),
    ]
