# Generated by Django 4.2 on 2023-12-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_skill_alter_category_name_alter_subcategory_name"),
        ("resume", "0004_remove_resume_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.ManyToManyField(
                related_name="resume", to="categories.skill", verbose_name="навыки"
            ),
        ),
    ]
