# Generated by Django 4.2 on 2023-12-17 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_skill_alter_category_name_alter_subcategory_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resume", "0005_resume_skills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resume",
            options={"verbose_name": "резюме", "verbose_name_plural": "резюме"},
        ),
        migrations.AlterField(
            model_name="resume",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.subcategory",
                verbose_name="подкатегория",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
