# Generated by Django 4.2 on 2023-12-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_skill_alter_category_name_alter_subcategory_name"),
        ("resume", "0006_alter_resume_options_alter_resume_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="resume",
                to="categories.skill",
                verbose_name="навыки",
            ),
        ),
    ]
