# Generated by Django 4.2 on 2023-12-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимальная длина - 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="имя",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Максимальная длина - 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="слаг",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        default="",
                        editable=False,
                        help_text="нормализованное имя навыка",
                        max_length=150,
                        verbose_name="нормализованное имя навыка",
                    ),
                ),
            ],
            options={
                "verbose_name": "навык",
                "verbose_name_plural": "навыки",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Максимальная длина - 150 символов",
                max_length=150,
                unique=True,
                verbose_name="имя",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(
                help_text="Максимальная длина - 150 символов",
                max_length=150,
                unique=True,
                verbose_name="имя",
            ),
        ),
    ]
