# Generated by Django 4.2 on 2023-12-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=254, verbose_name="имя"),
                ),
                ("mail", models.EmailField(max_length=254, verbose_name="почта")),
            ],
            options={
                "verbose_name": "данные к обращению",
                "verbose_name_plural": "данные к обращениям",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="дата и время создания",
                    ),
                ),
                (
                    "extra",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbackExtra",
                        related_query_name="FeedbackExtra",
                        to="feedback.feedbackextra",
                        verbose_name="доп. данные",
                    ),
                ),
            ],
            options={
                "verbose_name": "обращение",
                "verbose_name_plural": "обращения",
            },
        ),
    ]
