# Generated by Django 4.2 on 2023-12-17 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_skill_alter_category_name_alter_subcategory_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0003_job_skills_jobrequests"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"verbose_name": "работа", "verbose_name_plural": "работы"},
        ),
        migrations.AlterModelOptions(
            name="jobrequests",
            options={"verbose_name": "заявка", "verbose_name_plural": "заявки"},
        ),
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.subcategory",
                verbose_name="подкатегория",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="jobrequests",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Отправлено"), (2, "Одобрено"), (3, "Отклонено")],
                default=1,
                verbose_name="статус",
            ),
        ),
    ]
