# Generated by Django 4.2 on 2023-12-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_alter_job_options_alter_jobrequests_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="title",
            field=models.CharField(
                default=None, max_length=200, verbose_name="название"
            ),
            preserve_default=False,
        ),
    ]
