# Generated by Django 4.2 on 2023-12-18 20:40

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=jobs.models.Job._job_image_upload_to,
                verbose_name="изображение",
            ),
        ),
    ]
