# Generated by Django 4.2 on 2023-12-21 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0006_alter_resume_options_alter_resume_category_and_more"),
        ("jobs", "0006_alter_job_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="jobrequests",
            unique_together={("job", "resume")},
        ),
    ]
